# Generated by Django 4.2.5 on 2023-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
