# Generated by Django 4.2.5 on 2023-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_alter_form_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Content', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
    ]
