# Generated by Django 4.2.5 on 2023-10-02 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_contact_delete_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 22, 25, 5, 195510)),
        ),
    ]
