# Generated by Django 4.2.5 on 2023-10-02 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_contact_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Content',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 10, 2, 22, 27, 9, 528944)),
        ),
    ]
